language: node_js
node_js:
  - "0.10"
  - "0.11"

cache:
  directories:
    - node_modules

branches:
  except:
    - gh-pages

after_success:
  - "./tools/coverage"

deploy:
  provider: npm
  email: github-com@agachi.name
  on:
    tags: true
    repo: avaly/hapi-simple-session
    # Required due to https://github.com/travis-ci/travis-ci/issues/1675
    all_branches: true
